site_name: pboted documentation
site_url: https://pboted.readthedocs.io
site_description: pboted documentation
site_author: polistern

repo_url: https://github.com/polistern/pboted

nav:
- Home: index.md
- User Guide:
  - Installing: user-guide/install.md
  - Running: user-guide/run.md
  - Configuring: user-guide/configuration.md
  #- FAQ: user-guide/FAQ.md
- Tutorials:
  - AddressBook: tutorials/addressbook.md
  - SMTP: tutorials/SMTP.md
  - POP3: tutorials/POP3.md
- Developer Section:
  - Building from source:
    - Requirements: devs/building/requirements.md
    - Unix: devs/building/unix.md
  - Bote Protocol:
    - Version 5:
      - Description: devs/bote/v5/version5.md
      - Introduction: devs/bote/v5/introduction.md
      - Kademlia: devs/bote/v5/kademlia.md
      - Packet Types: devs/bote/v5/packet_types.md
      - Protocols: devs/bote/v5/protocols.md
      - Algorithms Used By Nodes Locally: devs/bote/v5/algorithms_used_by_nodes_locally.md
      - Files: devs/bote/v5/files.md
      - Cryptography: devs/bote/v5/cryptography.md
      - Glossary of Terms: devs/bote/v5/glossary_of_terms.md
    - Version 4:
      - Introduction: devs/bote/v4/introduction.md
      - Kademlia: devs/bote/v4/kademlia.md
      - Packet Types: devs/bote/v4/packet_types.md
      - Protocols: devs/bote/v4/protocols.md
      - Algorithms Used By Nodes Locally: devs/bote/v4/algorithms_used_by_nodes_locally.md
      - Files: devs/bote/v4/files.md
      - Cryptography: devs/bote/v4/cryptography.md
      - Glossary of Terms: devs/bote/v4/glossary_of_terms.md
    
- About:
  #- Community: about/community.md
  #- History: about/history.md
  - License: about/license.md
  - Special thanks: about/thanks.md
  #- Contributing: about/contributing.md

copyright: <a href="https://creativecommons.org/licenses/by-sa/4.0/">CC-BY-SA 4.0</a>, Maintained by polistern
theme: readthedocs

#markdown_extensions:
#  - admonition
#  - pymdownx.details
#  - pymdownx.superfences

theme:
  name: 'readthedocs'
  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
