site_name: pboted documentation
site_url: https://pboted.readthedocs.io
site_description: pboted documentation
site_author: polistern

repo_url: https://github.com/polistern/pboted_docs
repo_name: polistern/pboted_docs

nav:
- Home: index.md
- Beginning:
  - Installing: user-guide/install.md
  - Running: user-guide/run.md
  - Configuring: user-guide/configuration.md
  - Files: user-guide/files.md
  - Usage: user-guide/usage.md
- Tutorials:
  - Bootstrap: tutorials/bootstrap.md
  - AddressBook: tutorials/addressbook.md
  - SMTP: tutorials/SMTP.md
  - POP3: tutorials/POP3.md
  - Configuring the mail client: tutorials/mail_client.md
- Building from source:
  - Requirements: building/requirements.md
  - UNIX: building/unix.md
- Bote Protocol:
  - Version 5:
    - Description: bote/v5/version5.md
    - Glossary of Terms: bote/v5/glossary_of_terms.md
    - Introduction: bote/v5/introduction.md
    - Kademlia: bote/v5/kademlia.md
    - Packet Types: bote/v5/packet_types.md
    - Protocols: bote/v5/protocols.md
    - Cryptography: bote/v5/cryptography.md
  - Version 4:
    - Introduction: bote/v4/introduction.md
    - Kademlia: bote/v4/kademlia.md
    - Packet Types: bote/v4/packet_types.md
    - Protocols: bote/v4/protocols.md
    - Algorithms Used By Nodes Locally: bote/v4/algorithms_used_by_nodes_locally.md
    - Files: bote/v4/files.md
    - Cryptography: bote/v4/cryptography.md
    - Glossary of Terms: bote/v4/glossary_of_terms.md
- About:
  - License: about/license.md
  - Special thanks: about/thanks.md
  - Contributing: about/contributing.md
  - Donations: about/donations.md

copyright: <a href="https://creativecommons.org/licenses/by-sa/4.0/">CC-BY-SA 4.0</a>, Maintained by <a href="https://github.com/polistern">polistern</a>

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

plugins:
  - search
  - git-revision-date
  - i18n:
      default_language: en
      #no_translation:
      #  en: "This page isn't translated to English."
      #  ru: "Эта страница не переведена на Русский."
      languages:
        en:
          name: English
          build: true
          site_name: pboted
        ru:
          name: Russian
          build: true
          site_name: pboted
      #translate_nav:
      #  en:
      #    User Guide: "User Guide"
      #  ru:
      #    User Guide: "Руководство пользователя"
      nav_translations:
        ru:
          Home: Главная
          Beginning: Начало работы
          Installing: Установка
          Running: Запуск
          Configuring: Конфигурация
          Files: Файлы
          Usage: Использование
          #FAQ: 
          Tutorials: Руководства
          Bootstrap: Начальная загрузка
          AddressBook: Адресная книга
          #SMTP:
          #POP3:
          Configuring the mail client: Настройка почтового клиента
          Building from source: Сборка из исходников
          Requirements: Требования
          #UNIX: 
          Bote Protocol: Протокол Bote
          Version 5: Версия 5
          Description: Описание
          Glossary of Terms: Словарь терминов
          Introduction: Введение
          #Kademlia:
          Packet Types: Типы пакетов
          Protocols: Протоколы
          Cryptography: Криптография
          About: О проекте
          License: Лицензия
          Special thanks: Особые благодарности
          Contributing: Содействие
          Donations: Пожертвования

theme:
  name: 'material'
  palette:
    scheme: slate
    primary: green
  icon:
    repo: fontawesome/brands/github
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
