site_name: pboted documentation
site_url: https://pboted.readthedocs.io
site_description: pboted documentation
site_author: polistern

repo_url: https://github.com/polistern/pboted_docs
repo_name: polistern/pboted_docs

nav:
- Home: index.md
- User Guide:
  - Installing: user-guide/install.md
  - Running: user-guide/run.md
  - Configuring: user-guide/configuration.md
  - Usage: user-guide/usage.md
  - FAQ: user-guide/FAQ.md
- Tutorials:
  - AddressBook: tutorials/addressbook.md
  - SMTP: tutorials/SMTP.md
  - POP3: tutorials/POP3.md
  - Configuring the mail client: tutorials/mail_client.md
- Building from source:
  - Requirements: building/requirements.md
  - Unix: building/unix.md
- Bote Protocol:
  - Version 5:
    - Description: bote/v5/version5.md
    - Introduction: bote/v5/introduction.md
    - Kademlia: bote/v5/kademlia.md
    - Packet Types: bote/v5/packet_types.md
    - Protocols: bote/v5/protocols.md
    - Algorithms Used By Nodes Locally: bote/v5/algorithms_used_by_nodes_locally.md
    - Files: bote/v5/files.md
    - Cryptography: bote/v5/cryptography.md
    - Glossary of Terms: bote/v5/glossary_of_terms.md
  - Version 4:
    - Introduction: bote/v4/introduction.md
    - Kademlia: bote/v4/kademlia.md
    - Packet Types: bote/v4/packet_types.md
    - Protocols: bote/v4/protocols.md
    - Algorithms Used By Nodes Locally: bote/v4/algorithms_used_by_nodes_locally.md
    - Files: bote/v4/files.md
    - Cryptography: bote/v4/cryptography.md
    - Glossary of Terms: bote/v4/glossary_of_terms.md
- About:
  - License: about/license.md
  - Special thanks: about/thanks.md
  - Contributing: about/contributing.md
  - Donations: about/donations.md

copyright: <a href="https://creativecommons.org/licenses/by-sa/4.0/">CC-BY-SA 4.0</a>, Maintained by <a href="https://github.com/polistern">polistern</a>

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

plugins:
  - git-revision-date

theme:
  name: 'material'
  palette:
    scheme: slate
    primary: green
  icon:
    repo: fontawesome/brands/github
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
